version: '3.8'

services:
  app:
    build:
      context: . # Build context is the docker-ampnm folder
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/ # Mount the current directory into the container
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=network_monitor
      - DB_USER=user
      - DB_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - ADMIN_PASSWORD=password
      - LICENSE_API_URL=https://portal.itsupport.com.bd/verify_license.php # Ensure this matches your deployment
      - APP_LICENSE_KEY=YOUR_LICENSE_KEY_HERE # Replace with the actual license key
    ports:
      - "2266:2266"
    restart: unless-stopped

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: network_monitor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: