// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vfemkztsywpglqxjowif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmZW1renRzeXdwZ2xxeGpvd2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzODY2MTgsImV4cCI6MjA3NDk2MjYxOH0.XPFmRLtaGdzw_0hw7p74eR5Nh6RadMVPB3M0HAcqjTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);